"""empty message

Revision ID: 3b2efd6da478
Revises: 6f456354bea1
Create Date: 2018-06-21 23:00:53.266721

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3b2efd6da478'
down_revision = '6f456354bea1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task_result', sa.Column('parent_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_task_result_parent_id'), 'task_result', ['parent_id'], unique=False)
    op.create_foreign_key(None, 'task_result', 'task_result', ['parent_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'task_result', type_='foreignkey')
    op.drop_index(op.f('ix_task_result_parent_id'), table_name='task_result')
    op.drop_column('task_result', 'parent_id')
    # ### end Alembic commands ###
