"""empty message

Revision ID: 56c59adcfe10
Revises: 0bf6832fd1f2
Create Date: 2023-01-03 09:45:16.743950

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '56c59adcfe10'
down_revision = '0bf6832fd1f2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('periodic_task', sa.Column('queue', sa.String(length=200), nullable=True))
    op.add_column('periodic_task', sa.Column('exchange', sa.String(length=200), nullable=True))
    op.add_column('periodic_task', sa.Column('routing_key', sa.String(length=200), nullable=True))
    op.add_column('periodic_task', sa.Column('headers', sa.Text(), nullable=True))
    op.add_column('periodic_task', sa.Column('priority', sa.Integer(), nullable=True))
    op.add_column('periodic_task', sa.Column('expires', sa.DateTime(), nullable=True))
    op.add_column('periodic_task', sa.Column('expire_seconds', sa.Integer(), nullable=True))
    op.add_column('periodic_task', sa.Column('one_off', sa.Boolean(), nullable=True))
    op.add_column('periodic_task', sa.Column('start_time', sa.DateTime(), nullable=True))
    op.alter_column('periodic_task', 'name',
               existing_type=sa.VARCHAR(length=120),
               type_=sa.String(length=200),
               existing_nullable=True)
    op.alter_column('periodic_task', 'task',
               existing_type=sa.VARCHAR(length=120),
               type_=sa.String(length=200),
               existing_nullable=True)
    op.alter_column('periodic_task', 'args',
               existing_type=sa.VARCHAR(length=120),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('periodic_task', 'kwargs',
               existing_type=sa.VARCHAR(length=120),
               type_=sa.Text(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('periodic_task', 'kwargs',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=120),
               existing_nullable=True)
    op.alter_column('periodic_task', 'args',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=120),
               existing_nullable=True)
    op.alter_column('periodic_task', 'task',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=120),
               existing_nullable=True)
    op.alter_column('periodic_task', 'name',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=120),
               existing_nullable=True)
    op.drop_column('periodic_task', 'start_time')
    op.drop_column('periodic_task', 'one_off')
    op.drop_column('periodic_task', 'expire_seconds')
    op.drop_column('periodic_task', 'expires')
    op.drop_column('periodic_task', 'priority')
    op.drop_column('periodic_task', 'headers')
    op.drop_column('periodic_task', 'routing_key')
    op.drop_column('periodic_task', 'exchange')
    op.drop_column('periodic_task', 'queue')
    # ### end Alembic commands ###
